# #                                                      _      _            ___               
# #                                                     | \ _ _|_ _ __  _  _  |  _     _  __ _ 
# #                                                     |_/(/_ | (/_| |_> (/_ | (_)\^/(/_ | _> 
# #                                                     
# #                                                     			Configuration File
# #   
# #                    		Author: Achille Bourgault
# #   
# #   
# #   